FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod ./
# COPY go.sum ./
RUN go mod download
COPY . .
RUN go build -o ingestion-api ./cmd/ingestion-api/main.go


FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/ingestion-api .
EXPOSE 8080
CMD [ "./ingestion-api" ]